### ISSUE TITLE
Webserver fails to initialize

### ISSUE THREAD

**Issue by imfrompa** [worldwidewoogie/unifi-parental-controls#3]
I receive this error in the docker image as well as the direct install.  Any idea/thought?

`Status: Downloaded newer image for worldwidewoogie/unifi-parental-controls:latest
[2021-08-28 14:40:11.267] [LOG]    Listening on http://localhost:8080
[2021-08-28 14:40:12.135] [LOG]    Recalculating cron schedule
[2021-08-28 14:40:12.197] [ERROR]  AssertionError [ERR_ASSERTION]: config.privateKey does not exist at given fs path
    at new AssertionError (internal/assert/assertion_error.js:456:5)
    at NodeSSH.connect (/node/node_modules/node-ssh/lib/cjs/index.js:146:31) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: undefined
}
[2021-08-28 14:40:12.200] [LOG]    Shutting down
[2021-08-28 14:40:12.201] [LOG]    Closing web server
`

**Comment by worldwidewoogie** [comment]
Can you confirm that the file that config.privateKey points to exists and has the proper permissions? ssh can be picky about that.
